### ISSUE TITLE
ebs_block_devices variable prevents reuse of volumes

### ISSUE THREAD

**Issue by ringods** [skyscrapers/terraform-instances#33]
Commit ba80ce5982fe17df967050a278cd68f65e4f790a introduced the ability to add additional EBS block devices.

The Terraform [docs](https://www.terraform.io/docs/providers/aws/r/instance.html#ebs_block_device) mention this:

> **NOTE on EBS block devices:** If you use `ebs_block_device` on an `aws_instance`, Terraform will assume management over the full set of non-root EBS block devices for the instance, and treats additional block devices as drift. For this reason, `ebs_block_device` cannot be mixed with external `aws_ebs_volume` + `aws_volume_attachment` resources for a given instance.

I have a scenario where I want to use a specific EBS volume and always have it attached to the instance, even if that instance gets terminated by AWS.

I tried to create it with this module, passing this in as `var.ebs_block_devices` to the module:

```
  ebs_block_devices = [{
    device_name           = "/dev/sdh"
    volume_type           = "standard"
    volume_size           = 100
    delete_on_termination = false
  }]
```

When the instance is terminated, the volume is not deleted as requested by the `delete_on_termination` setting. When launching a replacement instance, the old volume is not reused but a new volume is created and attached.

Would it be OK to drop this `ebs_block_devices` support in favor of external `aws_ebs_volume` + `aws_volume_attachment`?

Via a `cloud-init` file, I can wait for all disks to be attached first. I have a working solution for one such disk like this:

```
#cloud-config
bootcmd:
  - 'while [ `lsblk | grep xvdh | wc -l` -lt 1 ]; do echo waiting on disks...; sleep 5; done'
disk_setup:
  /dev/xvdh:
    table_type: mbr
    layout:
      - 100
    overwrite: False
fs_setup: 
  - device: /dev/xvdh1
    partition: 1
    filesystem: ext4
mounts:
- [ /dev/xvdh1, /data ]
```

See the `bootcmd` specifically.
